### ISSUE TITLE
jQuery iframe size problem

### ISSUE THREAD

**Issue by danielkalen** [oscarotero/jquery-cheatsheet#1]
When opening the modal popup for a specific method, the inner iFrame gets loaded in minimal dimensions instead of stretching to the parent's size. I tested this on firefox and safari on os x 10.11.

**Comment by oscarotero** [comment]
Hello
I don't see this issue. Can i have a screenshot and the version of firefox/safari? Anyway, the last osx version is 10.10

**Comment by danielkalen** [comment]
Sorry on that typo there.
I'm running the latest safari and FF dev edition.

Now that I'm retesting it on FF, it seems like this issue is only apparent on safari and not FF. 
Sorry about that.

![screen shot](https://cloud.githubusercontent.com/assets/10832620/6082640/ed967e78-adf0-11e4-870e-22f1373b43a5.png)
![screen shot 1](https://cloud.githubusercontent.com/assets/10832620/6082641/eda8a5d0-adf0-11e4-9870-3b5c43b1eaf9.png)

**Comment by oscarotero** [comment]
Fixed. Thank you for the feedback :smile:
