### ISSUE TITLE
I think that it's more convenient

### ISSUE THREAD

**Issue by ArturGodunov** [oscarotero/jquery-cheatsheet#2]
Add some properties:
@media (min-width: 750px){
  .main-content {
      flex-wrap: wrap;
  }
}
.main-content article {
    flex-grow: 1;
}

**Comment by oscarotero** [comment]
Thank you for the suggestion. I think this can be usefull in some cases, but not in others (I use a macbook and for me it's easier the horizontal scroll with the trackpad). But I can add this feature as an option (like the ability to open the links in modal, new window or same window).

**Comment by oscarotero** [comment]
Just implemented!
Now you can choose the horizontal or vertical layout in the settings.
Feel free to reopen this if you see something wrong.
Thanks
